use anyhow::Result;
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;
use console::style;
use crate::db::ContextDb;
use crate::core::vector_store::VectorStore;
use crate::core::embedding::EmbeddingEngine;

pub struct ContextGenerator;

impl ContextGenerator {
    pub async fn generate(focus_query: Option<String>) -> Result<()> {
        let db_dir = Path::new(".database");
        let output_dir = Path::new(".amdb");

        if !output_dir.exists() {
            fs::create_dir(output_dir)?;
        }

        if !db_dir.exists() {
            println!("{}", style("Error: Database not found. Run 'amdb init' first.").red());
            return Ok(());
        }

        let db = ContextDb::open(db_dir)?;
        let target_files: Vec<String>;
        let output_filename: String;

        if let Some(query) = focus_query {
            let safe_name = query.replace(" ", "-").replace("/", "-").to_lowercase();
            output_filename = format!("{}.md", safe_name);

            println!("{}", style(format!("Filtering context for: '{}'...", query)).cyan());

            let vector_path = db_dir.join("vector");

            let store = VectorStore::open(&vector_path)?;
            let embedder = EmbeddingEngine::new()?;
            let query_vec = embedder.embed(&query)?;
            let results = store.search(&query_vec, 10)?;

            println!("DEBUG: Search found {} matches for query '{}'", results.len(), query);

            if results.is_empty() {
                println!("{}", style("No matches found. Falling back to full context.").yellow());
                target_files = db.get_all_files()?;
            } else {
                let mut paths = Vec::new();
                for (_, record) in results {
                    println!("DEBUG: Found relevant file: {}", record.file_path);

                    if !paths.contains(&record.file_path) {
                        paths.push(record.file_path);
                    }
                }
                target_files = paths;
            }
        }
        else {
            output_filename = "context.md".to_string();
            println!("{}", style("Generating full project context...").blue());
            target_files = db.get_all_files()?;
        }

        let output_path = output_dir.join(&output_filename);
        let mut content = String::new();

        content.push_str(&format!("# AI Context: {}\n\n", output_filename));
        content.push_str("> Auto-generated by amdb.\n\n");

        content.push_str("## File Summaries\n\n");
        for file_path in &target_files {
            let symbols = db.get_symbols(file_path)?;
            if symbols.is_empty() { continue; }

            content.push_str(&format!("### {}\n", file_path));

            for symbol in symbols {
                let doc = symbol.docstring.clone().unwrap_or_default();
                let summary = doc.lines().next().unwrap_or("").trim();

                content.push_str(&format!("- **{}** ({})", symbol.name, symbol.kind));
                if !summary.is_empty() {
                    content.push_str(&format!(": {}", summary));
                }
                content.push('\n');
            }
            content.push('\n');
        }

        content.push_str("## Dependency Graph\n```mermaid\ngraph TD;\n");
        let all_edges = db.get_all_relationships()?;
        let mut edge_count = 0;

        for edge in all_edges {
            if edge_count > 100 { break; }

            let caller = edge.caller.replace("::", "_").replace(".", "_");
            let callee = edge.callee.replace("::", "_").replace(".", "_");
            if caller != callee {
                content.push_str(&format!("    {} --> {};\n", caller, callee));
                edge_count += 1;
            }
        }
        content.push_str("```\n");

        let mut file = File::create(&output_path)?;
        file.write_all(content.as_bytes())?;

        println!("{}", style(format!("Generated: {}", output_path.display())).green().bold());
        Ok(())
    }
}